# Generated by Django 5.0.4 on 2024-05-29 20:41

import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0016_remove_user_birth_remove_user_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, unique=True
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "country",
                    models.CharField(blank=True, default="", max_length=5, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("m", "m"), ("f", "f")],
                        default="m",
                        max_length=5,
                        null=True,
                    ),
                ),
                ("birth", models.DateField(blank=True, default="2000-1-1", null=True)),
                (
                    "photo",
                    models.ImageField(
                        default="users/photos/default.png",
                        null=True,
                        upload_to="users/photos",
                    ),
                ),
                (
                    "token",
                    models.CharField(blank=True, default="", max_length=65, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("doctor", "doctor"), ("patient", "patient")],
                        default="patient",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("en", "en"), ("ar", "ar")],
                        default="en",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "public_key",
                    models.TextField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "private_key",
                    models.TextField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "*Users",
            },
            managers=[
                ("objects", users.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "clinic_address",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        default=0.0,
                        max_digits=2,
                        null=True,
                    ),
                ),
                (
                    "num_of_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        default=0.0,
                        max_digits=5,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor",
                "ordering": ["id"],
            },
            bases=("users.user",),
            managers=[
                ("objects", users.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "ordering": ["id"],
            },
            bases=("users.user",),
            managers=[
                ("objects", users.models.CustomUserManager()),
            ],
        ),
    ]
