# Generated by Django 5.0.4 on 2024-04-05 01:29

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0016_remove_user_birth_remove_user_country_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Abo",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="sy", max_length=50, null=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("m", "m"), ("f", "f")],
                        default="m",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("birth", models.DateField(blank=True, default="2000-1-1", null=True)),
                (
                    "photo",
                    models.ImageField(
                        default="users/photos/default.png",
                        null=True,
                        upload_to="users/photos",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("en", "en"), ("ar", "ar")],
                        default="en",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "token",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("doctor", "doctor"), ("patient", "patient")],
                        default="patient",
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
