# Generated by Django 5.0.4 on 2024-04-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_abo"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="birth",
            field=models.DateField(blank=True, default="2000-1-1", null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="country",
            field=models.CharField(blank=True, default="sy", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("m", "m"), ("f", "f")],
                default="m",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("en", "en"), ("ar", "ar")],
                default="en",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="photo",
            field=models.ImageField(
                default="users/photos/default.png", null=True, upload_to="users/photos"
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="token",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("doctor", "doctor"), ("patient", "patient")],
                default="patient",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="birth",
            field=models.DateField(blank=True, default="2000-1-1", null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="country",
            field=models.CharField(blank=True, default="sy", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("m", "m"), ("f", "f")],
                default="m",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("en", "en"), ("ar", "ar")],
                default="en",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="photo",
            field=models.ImageField(
                default="users/photos/default.png", null=True, upload_to="users/photos"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="token",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("doctor", "doctor"), ("patient", "patient")],
                default="patient",
                max_length=10,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="Abo",
        ),
    ]
