# Generated by Django 5.0.4 on 2024-04-05 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_doctor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctor",
            options={"ordering": ["id"], "verbose_name": "Doctor"},
        ),
        migrations.AlterModelOptions(
            name="patient",
            options={"ordering": ["id"], "verbose_name": "Patient"},
        ),
    ]
