# Generated by Django 5.0.4 on 2024-04-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="specialization",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
