# Generated by Django 5.0.4 on 2024-04-08 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_doctor_specialization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "*Users"},
        ),
    ]
