# Generated by Django 5.0.4 on 2024-04-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("en", "en"), ("ar", "ar")],
                default="en",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("doctor", "doctor"), ("patient", "patient")],
                default="patient",
                max_length=20,
                null=True,
            ),
        ),
    ]
