# Generated by Django 5.0.4 on 2024-04-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.CharField(blank=True, default="", max_length=65, null=True),
        ),
    ]
