# Generated by Django 5.0.4 on 2024-04-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_user_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="private_key",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="public_key",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
