# Generated by Django 5.0.4 on 2024-05-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_user_private_key_user_public_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="private_key",
            field=models.TextField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="public_key",
            field=models.TextField(blank=True, default="", max_length=500, null=True),
        ),
    ]
