# Generated by Django 5.0.4 on 2024-05-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="To_Do",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aim", models.CharField(max_length=100)),
                ("goal", models.CharField(max_length=100)),
                ("is_done", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "To_Do_list",
                "ordering": ["patient_id"],
            },
        ),
    ]
