# Generated by Django 5.0.4 on 2024-05-29 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("to_do_list", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="to_do",
            name="doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="doctor_appointments",
                to="users.doctor",
            ),
        ),
        migrations.AddField(
            model_name="to_do",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_appointments",
                to="users.patient",
            ),
        ),
    ]
