# Generated by Django 5.0.4 on 2024-06-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Huggingface_API",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Chack_Email_URL",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Chack_Email_API_KEY",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Chack_Email_API_HOST",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Send_Mail_API_KEY1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Send_Mail_API_HOST1",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Send_Mail_URL",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Send_Mail_API_KEY2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Send_Mail_API_HOST2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Whatsapp_URL",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Whatsapp_API_KEY",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Whatsapp_API_HOST",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
