# Generated by Django 5.0.4 on 2024-06-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setting_apps", "0002_rename_send_mail_url_data_send_mail_url1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="Whatsapp_Token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
