# Generated by Django 5.0.4 on 2024-05-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor", models.EmailField(blank=True, default="", max_length=254)),
                ("patient", models.EmailField(blank=True, default="", max_length=254)),
                ("music_path", models.FilePathField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
            ],
        ),
    ]
