# Generated by Django 5.0.4 on 2024-06-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sounds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="music_path",
            field=models.FileField(blank=True, null=True, upload_to="sounds/music"),
        ),
    ]
