# Generated by Django 5.0.4 on 2024-06-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sounds", "0002_alter_music_music_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="sounds/music/"),
        ),
        migrations.AlterField(
            model_name="music",
            name="music_path",
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
