# Generated by Django 5.0.4 on 2024-06-01 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sounds", "0003_music_audio_file_alter_music_music_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="music",
            name="audio_file",
        ),
    ]
