# Generated by Django 5.0.4 on 2024-06-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sounds", "0004_remove_music_audio_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="music",
            name="music_path",
        ),
        migrations.AddField(
            model_name="music",
            name="music",
            field=models.FileField(blank=True, null=True, upload_to="sounds/music"),
        ),
    ]
