# Generated by Django 5.0.4 on 2024-06-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sounds", "0005_remove_music_music_path_music_music"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="music_path",
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
