# Generated by Django 5.0.4 on 2024-06-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sounds", "0006_music_music_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="music_path",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
