# Generated by Django 5.0.4 on 2024-06-05 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sounds", "0007_alter_music_music_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="music",
            name="music",
        ),
    ]
