# Generated by Django 5.0.4 on 2024-04-05 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0006_alter_user_options_user_first_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Panic_Disorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Positive_Negative", models.BooleanField(blank=True, null=True)),
                ("Family_History", models.IntegerField(blank=True, null=True)),
                ("Personal_History", models.IntegerField(blank=True, null=True)),
                ("Current_Stressors", models.IntegerField(blank=True, null=True)),
                ("Symptoms", models.IntegerField(blank=True, null=True)),
                ("Severity", models.IntegerField(blank=True, null=True)),
                ("Impact_on_Life", models.IntegerField(blank=True, null=True)),
                ("Demographics", models.IntegerField(blank=True, null=True)),
                ("Medical_History", models.IntegerField(blank=True, null=True)),
                ("Psychiatric_History", models.IntegerField(blank=True, null=True)),
                ("Substance_Use", models.IntegerField(blank=True, null=True)),
                ("Coping_Mechanisms", models.IntegerField(blank=True, null=True)),
                ("Social_Support", models.IntegerField(blank=True, null=True)),
                ("Lifestyle_Factors", models.IntegerField(blank=True, null=True)),
                (
                    "Doctor_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Doctor_Id",
                        to="users.doctor",
                    ),
                ),
                (
                    "Person_Id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Person_Id",
                        to="users.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Panic_Disorder",
                "ordering": ["Person_Id"],
            },
        ),
    ]
