# Generated by Django 5.0.4 on 2024-05-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Iris",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("das1", models.IntegerField(blank=True, null=True)),
                ("das2", models.IntegerField(blank=True, null=True)),
                ("das3", models.IntegerField(blank=True, null=True)),
                ("das4", models.IntegerField(blank=True, null=True)),
                ("das5", models.IntegerField(blank=True, null=True)),
                ("das6", models.IntegerField(blank=True, null=True)),
                ("das7", models.IntegerField(blank=True, null=True)),
                ("das8", models.IntegerField(blank=True, null=True)),
                ("das_d", models.BooleanField(blank=True, default=False, null=True)),
                ("das_a", models.BooleanField(blank=True, default=False, null=True)),
                ("das_s", models.BooleanField(blank=True, default=False, null=True)),
                ("Age", models.IntegerField(blank=True, null=True)),
                ("Gender", models.CharField(blank=True, max_length=35, null=True)),
                (
                    "Family_History",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                (
                    "Personal_History",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                (
                    "Current_Stressors",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                ("Symptoms", models.CharField(blank=True, max_length=35, null=True)),
                ("Severity", models.CharField(blank=True, max_length=35, null=True)),
                (
                    "Impact_on_Life",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                (
                    "Demographics",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                (
                    "Medical_History",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                (
                    "Psychiatric_History",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                (
                    "Substance_Use",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                (
                    "Coping_Mechanisms",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                (
                    "Social_Support",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                (
                    "Lifestyle_Factors",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                ("Positive_Negative_panic", models.BooleanField(blank=True, null=True)),
                ("Sadness", models.CharField(blank=True, max_length=35, null=True)),
                ("Euphoric", models.CharField(blank=True, max_length=35, null=True)),
                ("Exhausted", models.CharField(blank=True, max_length=35, null=True)),
                (
                    "Sleep_Dissorder",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                ("Mood_Swing", models.CharField(blank=True, max_length=35, null=True)),
                (
                    "Suicidal_Thoughts",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                ("Anorxia", models.CharField(blank=True, max_length=35, null=True)),
                (
                    "Authority_Respect",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                (
                    "Try_Explanation",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                (
                    "Aggressive_Response",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                (
                    "Ignore_And_Move_On",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                (
                    "Nervous_BreakDown",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                (
                    "Admit_Mistakes",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                (
                    "Overthinking",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                (
                    "Sexual_Activity",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                (
                    "Concentration",
                    models.CharField(blank=True, max_length=35, null=True),
                ),
                ("Optimisim", models.CharField(blank=True, max_length=35, null=True)),
                (
                    "Expert_Diagnose",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bipolar Type-1", "Bipolar Type-1"),
                            ("Bipolar Type-2", "Bipolar Type-2"),
                            ("Depression", "Depression"),
                            ("Normal", "Normal"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "IRIS",
            },
        ),
    ]
