# Generated by Django 5.0.4 on 2024-04-05 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("irisApp", "0001_initial"),
        ("users", "0007_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="panic_disorder",
            name="Person_Id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Person_Id",
                to="users.patient",
            ),
        ),
    ]
