# Generated by Django 5.0.4 on 2024-05-29 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("irisApp", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="iris",
            name="Doctor_email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Doctor_Id",
                to="users.doctor",
            ),
        ),
        migrations.AddField(
            model_name="iris",
            name="Person_email",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Person_Id",
                to="users.patient",
            ),
        ),
    ]
