# Generated by Django 5.0.4 on 2024-05-13 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("irisApp", "0003_alter_panic_disorder_options_and_more"),
        ("users", "0014_alter_user_private_key_alter_user_public_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="Iris",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("das1", models.IntegerField(blank=True, null=True)),
                ("das2", models.IntegerField(blank=True, null=True)),
                ("das3", models.IntegerField(blank=True, null=True)),
                ("das4", models.IntegerField(blank=True, null=True)),
                ("das5", models.IntegerField(blank=True, null=True)),
                ("das6", models.IntegerField(blank=True, null=True)),
                ("das7", models.IntegerField(blank=True, null=True)),
                ("das8", models.IntegerField(blank=True, null=True)),
                ("das_d", models.BooleanField(blank=True, default=False, null=True)),
                ("das_a", models.BooleanField(blank=True, default=False, null=True)),
                ("das_s", models.BooleanField(blank=True, default=False, null=True)),
                ("Family_History", models.IntegerField(blank=True, null=True)),
                ("Personal_History", models.IntegerField(blank=True, null=True)),
                ("Current_Stressors", models.IntegerField(blank=True, null=True)),
                ("Symptoms", models.IntegerField(blank=True, null=True)),
                ("Severity", models.IntegerField(blank=True, null=True)),
                ("Impact_on_Life", models.IntegerField(blank=True, null=True)),
                ("Demographics", models.IntegerField(blank=True, null=True)),
                ("Medical_History", models.IntegerField(blank=True, null=True)),
                ("Psychiatric_History", models.IntegerField(blank=True, null=True)),
                ("Substance_Use", models.IntegerField(blank=True, null=True)),
                ("Coping_Mechanisms", models.IntegerField(blank=True, null=True)),
                ("Social_Support", models.IntegerField(blank=True, null=True)),
                ("Lifestyle_Factors", models.IntegerField(blank=True, null=True)),
                ("Positive_Negative", models.BooleanField(blank=True, null=True)),
                ("Sadness", models.IntegerField(blank=True, null=True)),
                ("Euphoric", models.IntegerField(blank=True, null=True)),
                ("Exhausted", models.IntegerField(blank=True, null=True)),
                ("Sleep_Dissorder", models.IntegerField(blank=True, null=True)),
                ("Mood_Swing", models.IntegerField(blank=True, null=True)),
                ("Suicidal_Thoughts", models.IntegerField(blank=True, null=True)),
                ("Anorxia", models.IntegerField(blank=True, null=True)),
                ("Authority_Respect", models.IntegerField(blank=True, null=True)),
                ("Try_Explanation", models.IntegerField(blank=True, null=True)),
                ("Aggressiv_Response", models.IntegerField(blank=True, null=True)),
                ("Ignore_And_Move_On", models.IntegerField(blank=True, null=True)),
                ("Nervous_BreakDown", models.IntegerField(blank=True, null=True)),
                ("Admin_Mistakes", models.IntegerField(blank=True, null=True)),
                ("Overthinking", models.IntegerField(blank=True, null=True)),
                ("Sexual_Activity", models.IntegerField(blank=True, null=True)),
                ("Concentration", models.IntegerField(blank=True, null=True)),
                ("Optimisim", models.IntegerField(blank=True, null=True)),
                ("Expert_Diagnose", models.IntegerField(blank=True, null=True)),
                (
                    "Doctor_email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="Doctor_Id",
                        to="users.doctor",
                    ),
                ),
                (
                    "Person_email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Person_Id",
                        to="users.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "IRIS",
            },
        ),
        migrations.DeleteModel(
            name="Panic_Disorder",
        ),
    ]
