# Generated by Django 5.0.4 on 2024-05-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("irisApp", "0004_iris_delete_panic_disorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="iris",
            name="Age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="iris",
            name="Gender",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
