# Generated by Django 5.0.4 on 2024-06-16 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("irisApp", "0004_alter_iris_person_email"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iris",
            name="Person_email",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Person_Id",
                to="users.patient",
            ),
        ),
    ]
