# Generated by Django 5.0.4 on 2024-06-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("irisApp", "0005_alter_iris_person_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iris",
            name="depressed",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
