# Generated by Django 5.0.4 on 2024-05-14 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("irisApp", "0005_iris_age_iris_gender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="iris",
            old_name="Positive_Negative",
            new_name="Positive_Negative_panic",
        ),
    ]
