# Generated by Django 5.0.4 on 2024-05-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("irisApp", "0006_rename_positive_negative_iris_positive_negative_panic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iris",
            name="Expert_Diagnose",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
