# Generated by Django 5.0.4 on 2024-05-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("irisApp", "0007_alter_iris_expert_diagnose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iris",
            name="Expert_Diagnose",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bipolar Type-1", "Bipolar Type-1"),
                    ("Bipolar Type-2", "Bipolar Type-2"),
                    ("Depression", "Depression"),
                    ("Normal", "Normal"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
