# Generated by Django 5.0.4 on 2024-06-26 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("irisApp", "0007_historicaliris"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalIris",
        ),
    ]
