# Generated by Django 5.0.4 on 2024-07-02 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("irisApp", "0008_delete_historicaliris"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="iris",
            options={"verbose_name": "Test", "verbose_name_plural": "Test"},
        ),
    ]
