# Generated by Django 5.0.4 on 2024-05-28 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("irisApp", "0008_alter_iris_expert_diagnose"),
        ("users", "0014_alter_user_private_key_alter_user_public_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iris",
            name="Person_email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Person_Id",
                to="users.patient",
                unique=True,
            ),
        ),
    ]
