# Generated by Django 5.0.4 on 2024-05-28 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("irisApp", "0010_alter_iris_person_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="iris",
            old_name="Admin_Mistakes",
            new_name="Admit_Mistakes",
        ),
        migrations.RenameField(
            model_name="iris",
            old_name="Aggressiv_Response",
            new_name="Aggressive_Response",
        ),
        migrations.RenameField(
            model_name="iris",
            old_name="Nervous_BreakDown",
            new_name="Nervous_Breakdown",
        ),
    ]
