# Generated by Django 5.0.4 on 2024-05-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("irisApp", "0011_rename_admin_mistakes_iris_admit_mistakes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="iris",
            name="Nervous_Breakdown",
        ),
        migrations.AlterField(
            model_name="iris",
            name="Admit_Mistakes",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Aggressive_Response",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Anorxia",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Authority_Respect",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Concentration",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Euphoric",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Exhausted",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Ignore_And_Move_On",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Mood_Swing",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Optimisim",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Overthinking",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Sadness",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Sexual_Activity",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Sleep_Dissorder",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Suicidal_Thoughts",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Try_Explanation",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name="iris",
            name="Nervous_BreakDown",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
