# Generated by Django 5.0.4 on 2024-05-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("irisApp", "0012_remove_iris_nervous_breakdown_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iris",
            name="Coping_Mechanisms",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Current_Stressors",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Demographics",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Family_History",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Gender",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Impact_on_Life",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Lifestyle_Factors",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Medical_History",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Personal_History",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Psychiatric_History",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Severity",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Social_Support",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Substance_Use",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name="iris",
            name="Symptoms",
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
